services:
  db:
    container_name: todos-db
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todos
    ports:
      - 5455:5432
    volumes:
      - todos_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  todos_data:

networks:
  backend:
