services:
  db:
    container_name: comments-db
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=comments
    ports:
      - 5454:5432
    volumes:
      - comments_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  comments_data:

networks:
  backend:
